<a href="https://colab.research.google.com/github/varun2068/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
import sys
import numpy as np

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 5, 4])

In [ ]:
print(a[0])

1


To Find the Dimension of the array

In [ ]:
a.ndim

1

To Find the size of array

In [ ]:
a.size

5

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[[1, 2, -1]]

array([2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array([0.0, 1.0, 2.0, 3.0, 4.0])

In [ ]:
b.dtype

dtype('float64')

# **Dimensions And Shape**

In [ ]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6]])

To Find the shape of Array

In [ ]:
A.shape

(2, 3)

Dimension of Array

In [ ]:
A.ndim

2

In [ ]:
A.size

6

##**3D Array**

In [ ]:
B = np.array([
              [
               [12, 23, 34],
               [21, 32, 43],
              ],
              [
               [45, 56, 67],
               [76, 65, 54],
              ]
])

In [ ]:
B.size

12

In [ ]:
B.ndim

3

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.dtype

dtype('int64')

#**Indexing And Slicing Of Matrices**

In [ ]:
#Square Matrix
A = np.array([[1, 2, 3,],
             [4, 5, 6],
             [7, 8, 9]])

In [ ]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[2]

array([7, 8, 9])

In [ ]:
A[0]

array([1, 2, 3])

In [ ]:
A[1,2]

6

In [ ]:
A[1][2]

6

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A[1]

array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A[2]

array([99, 99, 99])

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#**Summary Statistics**

In [ ]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
#Variance
A.var()

6.666666666666667

In [ ]:
#standard deviation
A.std()

2.581988897471611

In [ ]:
# Sum of first Column
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

#**Broadcasting And Vectorized operations**

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10


array([ 0, 10, 20, 30])

In [ ]:
a == 100

array([False, False, False, False])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
l = [0, 1, 2, 3, 4]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30, 40]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
n = np.array([10, 10, 10, 10])

In [ ]:
a + n

array([10, 11, 12, 13])

In [ ]:
a * n

array([ 0, 10, 20, 30])

#**Boolean Arrays**

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a == 2

array([False, False,  True, False])

In [ ]:
a == 1

array([False,  True, False, False])

In [ ]:
a == 3

array([False, False, False,  True])

As in above the number 3 is present at last position that's why it show True else all False

In [ ]:
a == 4

array([False, False, False, False])

In above code 4 is not present in arrays that's why the ouput is False all element.

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a> a.mean()]

array([2, 3])

In [ ]:
a[~(a> a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a == 0)& (a == 1)]

array([], dtype=int64)

In [ ]:
a[(a == 2) & (a % 2 == 0)]

array([2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[67, 32,  0],
       [73,  8,  5],
       [77, 15, 36]])

In [ ]:
A[np.array([
           [True, False, True,],
           [False, True, False],
           [True, False, True]
])]

array([67,  0,  8, 77, 36])

In [ ]:
A > 30

array([[ True,  True, False],
       [ True, False, False],
       [ True, False,  True]])

#**Linear Algebra**

In [ ]:
A = np.array([[1, 2, 3,],
              [2, 3, 4],
              [3, 4, 5]
])

In [ ]:
B = np.array([[1, 2],
              [2, 3],
              [3, 4]
])

In [ ]:
A.dot(B)

array([[14, 20],
       [20, 29],
       [26, 38]])

In [ ]:
A @ B

array([[14, 20],
       [20, 29],
       [26, 38]])

In [ ]:
B.T

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
B.T @ A

array([[14, 20, 26],
       [20, 29, 38]])

#** Size of Object In Memory**

In [ ]:
# An Integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even much larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
np.dtype(float).itemsize

8

In [ ]:
# Lists are even Larger
sys.getsizeof([1])

80

In [ ]:
# In Numpy
np.array([1]).nbytes

8

###**Performance is also important**

In [ ]:
l = list(range(1000))

In [ ]:
a = np.arange(1000)

In [ ]:
%time np.sum(a**2)

CPU times: user 126 µs, sys: 12 µs, total: 138 µs
Wall time: 431 µs


332833500

In [ ]:
%time sum([x**2 for x in l])

CPU times: user 479 µs, sys: 43 µs, total: 522 µs
Wall time: 529 µs


332833500

#**Useful Numpy Functions**

####*random*


In [ ]:
np.random.random(size=2)

array([0.81663245, 0.84093393])

In [ ]:
np.random.normal(size=2)

array([ 0.62943336, -0.4167389 ])

In [ ]:
np.random.rand(2, 4)

array([[0.12676571, 0.36792264, 0.72746006, 0.46346307],
       [0.01158264, 0.57377684, 0.8979199 , 0.74606611]])

####*arange*

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

####*reshape*

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####*linspace*

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

####*zero, ones and empty*

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.empty([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

####*Code and Eye*

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'